version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    open-pull-requests-limit: 10
    reviewers:
      - "JGiter"
      - "jrhender"
